import {
  InvestigationModel,
  AgentModel,
  EvidenceModel,
  EntityModel,
  SignalModel,
  RelationshipModel,
  RecommendationModel,
  TimelineEventModel,
  WatchlistModel,
  AlertModel,
  SourceModel,
} from '@/lib/types';

export const seedInvestigation: InvestigationModel = {
  id: 'inv-001',
  title: 'NVIDIA × Generative AI',
  objective: "Analyze NVIDIA's position in Generative AI and identify emerging competitive threats and opportunities.",
  status: 'COMPLETED',
  priority: 'HIGH',
  timeHorizon: 'Last 30 days',
  primaryEntities: ['NVIDIA', 'Generative AI', 'TSMC', 'Cerebras', 'OpenAI'],
  createdAt: '2026-08-20T10:00:00.000Z',
  updatedAt: '2026-08-22T10:30:00.000Z',
  startedAt: '2026-08-20T10:00:00.000Z',
  completedAt: '2026-08-22T10:30:00.000Z',
  progress: 100,
  confidence: 94,
  threatScore: 68,
  opportunityScore: 74,
  signalVelocity: 42,
  orchestratorStatus: '● COMPLETE',
  orchestratorAction: 'Investigation complete. Autonomous monitoring active.',
  executiveSummary: "NVIDIA's position in Generative AI is strengthening rapidly based on cross-source correlation. However, custom hyperscaler silicon poses a medium-high long-term margin threat.",
  whyThisMatters: 'Software ecosystem moat combined with proprietary interconnect lock-in ensures short-term market dominance, but workload diversification requires immediate strategic positioning.',
};

export const seedAgents: AgentModel[] = [
  {
    id: 'agent-orch',
    name: 'RadarX Orchestrator',
    type: 'ORCHESTRATOR',
    role: 'Central Dispatcher & Strategy Planner',
    status: 'COMPLETE',
    currentTask: 'Investigation complete. Monitoring active streams.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 48,
    confidence: 96,
    color: '#D4AF37',
    lastActive: 'Just now',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-res',
    name: 'Research Agent',
    type: 'RESEARCH',
    role: 'Academic & arXiv Literature Search',
    status: 'COMPLETE',
    currentTask: 'Found 18 preprints on sub-linear attention mechanisms.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 15,
    confidence: 91,
    color: '#06B6D4',
    lastActive: '5m ago',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-pat',
    name: 'Patent Agent',
    type: 'PATENT',
    role: 'USPTO & Global Patent IP Analysis',
    status: 'COMPLETE',
    currentTask: 'Analyzed 3 newly published USPTO tensor filings.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 12,
    confidence: 94,
    color: '#D97706',
    lastActive: '3m ago',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-news',
    name: 'News Agent',
    type: 'NEWS',
    role: 'Financial Media & Press Analysis',
    status: 'COMPLETE',
    currentTask: 'Scanned 14 Bloomberg & Reuters market disclosures.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 9,
    confidence: 89,
    color: '#3B82F6',
    lastActive: '2m ago',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-comp',
    name: 'Competitor Agent',
    type: 'COMPETITOR',
    role: 'SEC Filings & Product Roadmap Tracker',
    status: 'COMPLETE',
    currentTask: 'Tracked AMD & Cerebras supply agreements.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 10,
    confidence: 88,
    color: '#059669',
    lastActive: '1m ago',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-web',
    name: 'Web Intelligence Agent',
    type: 'WEB',
    role: 'Open-source Code & Forum Scraping',
    status: 'COMPLETE',
    currentTask: 'Validated CUDA repository commit frequency.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 8,
    confidence: 90,
    color: '#8B5CF6',
    lastActive: 'Just now',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-sig',
    name: 'Signal Agent',
    type: 'SIGNAL',
    role: 'Cross-Source Anomaly Correlation',
    status: 'COMPLETE',
    currentTask: 'Correlated patent spike with GitHub commit velocity.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 10,
    confidence: 93,
    color: '#EC4899',
    lastActive: 'Just now',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'agent-syn',
    name: 'Synthesis Agent',
    type: 'SYNTHESIS',
    role: 'Executive Intelligence & Decision Matrix',
    status: 'COMPLETE',
    currentTask: 'Compiled unified intelligence report for executive review.',
    currentInvestigationId: 'inv-001',
    evidenceProcessed: 14,
    confidence: 95,
    color: '#C9A227',
    lastActive: 'Just now',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
  },
];

export const seedEvidence: EvidenceModel[] = [
  {
    id: 'ev-001',
    investigationId: 'inv-001',
    title: 'USPTO Patent Filing: Sub-Byte Quantization Hardware Acceleration',
    summary: 'NVIDIA filed a patent detailing low-precision INT4/FP4 matrix multiply-accumulate hardware units natively embedded in next-gen Tensor Cores.',
    source: 'USPTO Database',
    sourceType: 'PATENT',
    url: 'https://uspto.gov/patents/example-1001',
    publishedAt: '2026-08-18',
    discoveredAt: '2026-08-20T10:32:00Z',
    entityIds: ['ent-nvda', 'ent-fp4'],
    agentId: 'agent-pat',
    relevanceScore: 0.95,
    confidence: 94,
    metrics: [{ label: 'FP4 Speedup', value: '2.4x' }, { label: 'Efficiency', value: '+40%' }],
    createdAt: '2026-08-20T10:32:00Z',
  },
  {
    id: 'ev-002',
    investigationId: 'inv-001',
    title: 'arXiv Preprint: Sub-Linear Attention Memory Kernels for Blackwell',
    summary: 'Researchers published memory-efficient kernel implementations reducing KV cache footprint by 60% without perplexity degradation.',
    source: 'arXiv.org',
    sourceType: 'RESEARCH',
    url: 'https://arxiv.org/abs/2608.01234',
    publishedAt: '2026-08-19',
    discoveredAt: '2026-08-20T10:35:00Z',
    entityIds: ['ent-nvda', 'ent-[#06B6D4]'],
    agentId: 'agent-res',
    relevanceScore: 0.92,
    confidence: 91,
    metrics: [{ label: 'KV Cache Reduction', value: '60%' }],
    createdAt: '2026-08-20T10:35:00Z',
  },
  {
    id: 'ev-003',
    investigationId: 'inv-001',
    title: 'SEC 8-K: Hyperscaler Custom ASIC Capex Allocation',
    summary: 'Major cloud provider disclosures indicate 25% of 2027 inference capex will be directed to internal custom ASIC silicon.',
    source: 'SEC EDGAR',
    sourceType: 'PUBLIC_DATA',
    url: 'https://sec.gov/edgar/example-8k',
    publishedAt: '2026-08-15',
    discoveredAt: '2026-08-20T10:40:00Z',
    entityIds: ['ent-nvda', 'ent-[#D97706]'],
    agentId: 'agent-comp',
    relevanceScore: 0.88,
    confidence: 88,
    metrics: [{ label: 'Inference ASIC Shift', value: '25%' }],
    createdAt: '2026-08-20T10:40:00Z',
  },
  {
    id: 'ev-004',
    investigationId: 'inv-001',
    title: 'Bloomberg: TSMC Packaging Capacity Expansion Agreed with NVIDIA',
    summary: 'TSMC has reserved an additional 30% CoWoS advanced packaging capacity specifically for next-gen NVLink interconnect clusters.',
    source: 'Bloomberg News',
    sourceType: 'NEWS',
    url: 'https://bloomberg.com/news/articles/2026-08-17',
    publishedAt: '2026-08-17',
    discoveredAt: '2026-08-20T10:45:00Z',
    entityIds: ['ent-nvda', 'ent-tsmc'],
    agentId: 'agent-news',
    relevanceScore: 0.90,
    confidence: 90,
    metrics: [{ label: 'CoWoS Capacity', value: '+30%' }],
    createdAt: '2026-08-20T10:45:00Z',
  },
  {
    id: 'ev-005',
    investigationId: 'inv-001',
    title: 'GitHub Commit Spike: CUDA FP4 Optimization Repositories',
    summary: 'Open-source repository commit velocity for cuBLAS-FP4 bindings surged by 180% week-over-week.',
    source: 'GitHub API',
    sourceType: 'WEB',
    url: 'https://github.com/NVIDIA/cuda-samples',
    publishedAt: '2026-08-20',
    discoveredAt: '2026-08-20T10:50:00Z',
    entityIds: ['ent-nvda', 'ent-cuda'],
    agentId: 'agent-web',
    relevanceScore: 0.89,
    confidence: 89,
    metrics: [{ label: 'Commit Velocity', value: '+180%' }],
    createdAt: '2026-08-20T10:50:00Z',
  },
];

export const seedEntities: EntityModel[] = [
  {
    id: 'ent-nvda',
    name: 'NVIDIA Corporation',
    type: 'COMPANY',
    description: 'Leading GPU hardware and software platform provider for accelerated computing and AI.',
    confidence: 98,
    summary: 'Controls ~85% of tier-1 cloud AI training and inference accelerator deployments.',
    website: 'https://nvidia.com',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
  {
    id: 'ent-genai',
    name: 'Generative AI Workloads',
    type: 'RESEARCH_TOPIC',
    description: 'Large language models, multimodal transformers, and diffusion inference architectures.',
    confidence: 95,
    summary: 'Primary growth driver for enterprise datacenter compute spending.',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
  {
    id: 'ent-fp4',
    name: 'FP4 Quantization Standard',
    type: 'TECHNOLOGY',
    description: 'Sub-byte 4-bit floating point precision arithmetic for neural network inference.',
    confidence: 94,
    summary: 'Enables 2x model density per GPU node without loss of output accuracy.',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
  {
    id: 'ent-tsmc',
    name: 'TSMC',
    type: 'COMPANY',
    description: 'Semiconductor foundry provider supplying advanced CoWoS packaging.',
    confidence: 96,
    summary: 'Critical manufacturing partner for NVIDIA GPU packaging.',
    website: 'https://tsmc.com',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
  {
    id: 'ent-cerebras',
    name: 'Cerebras Systems',
    type: 'COMPANY',
    description: 'Wafer-scale AI inference system manufacturer competing in high-throughput inference.',
    confidence: 89,
    summary: 'Emerging competitor offering high memory bandwidth wafer-scale engines.',
    website: 'https://cerebras.ai',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
  {
    id: 'ent-cuda',
    name: 'CUDA Software Ecosystem',
    type: 'TECHNOLOGY',
    description: 'NVIDIA parallel computing platform and programming model.',
    confidence: 97,
    summary: 'Primary developer moat preventing migration to alternative accelerator hardware.',
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-22T00:00:00Z',
  },
];

export const seedRelationships: RelationshipModel[] = [
  {
    id: 'rel-001',
    investigationId: 'inv-001',
    sourceEntityId: 'ent-nvda',
    targetEntityId: 'ent-fp4',
    relationshipType: 'DEVELOPS',
    confidence: 96,
    evidenceIds: ['ev-001'],
    whyConnected: 'USPTO patent filings indicate native FP4 hardware execution units embedded in next-gen Tensor Cores.',
    createdAt: '2026-08-20T10:35:00Z',
  },
  {
    id: 'rel-002',
    investigationId: 'inv-001',
    sourceEntityId: 'ent-nvda',
    targetEntityId: 'ent-tsmc',
    relationshipType: 'PARTNERED_WITH',
    confidence: 95,
    evidenceIds: ['ev-004'],
    whyConnected: 'CoWoS packaging agreements expanded to support NVLink 5 scale-out clusters.',
    createdAt: '2026-08-20T10:45:00Z',
  },
  {
    id: 'rel-003',
    investigationId: 'inv-001',
    sourceEntityId: 'ent-cerebras',
    targetEntityId: 'ent-nvda',
    relationshipType: 'COMPETES_WITH',
    confidence: 90,
    evidenceIds: ['ev-003'],
    whyConnected: 'Wafer-scale engines target enterprise real-time inference latency benchmark supremacy.',
    createdAt: '2026-08-20T10:40:00Z',
  },
  {
    id: 'rel-004',
    investigationId: 'inv-001',
    sourceEntityId: 'ent-nvda',
    targetEntityId: 'ent-cuda',
    relationshipType: 'DEVELOPS',
    confidence: 98,
    evidenceIds: ['ev-005'],
    whyConnected: 'Open-source GitHub CUDA commits indicate developer lock-in for FP4 runtimes.',
    createdAt: '2026-08-20T10:50:00Z',
  },
];

export const seedSignals: SignalModel[] = [
  {
    id: 'sig-001',
    investigationId: 'inv-001',
    title: 'AI Infrastructure Acceleration',
    summary: 'Correlated spike across USPTO patents, arXiv preprints, and open-source CUDA repositories pointing to native FP4 hardware defaults.',
    impact: 'HIGH',
    confidence: 94,
    momentum: 42,
    status: 'VALIDATED',
    evidenceIds: ['ev-001', 'ev-002', 'ev-005'],
    entityIds: ['ent-nvda', 'ent-fp4'],
    sourceTypes: ['PATENT', 'RESEARCH', 'WEB'],
    detectedAt: '2026-08-20T11:00:00Z',
    validatedAt: '2026-08-22T10:00:00Z',
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'sig-002',
    investigationId: 'inv-001',
    title: 'Hyperscaler Custom ASIC Capex Shift',
    summary: 'Cloud providers allocating up to 25% of inference budget to proprietary silicon, pressuring long-term hardware margins.',
    impact: 'HIGH',
    confidence: 88,
    momentum: 28,
    status: 'DETECTED',
    evidenceIds: ['ev-003'],
    entityIds: ['ent-nvda'],
    sourceTypes: ['PUBLIC_DATA', 'NEWS'],
    detectedAt: '2026-08-21T09:15:00Z',
    createdAt: '2026-08-21T09:15:00Z',
  },
  {
    id: 'sig-003',
    investigationId: 'inv-001',
    title: 'TSMC CoWoS Capacity Expansion',
    summary: '30% increase in reserved advanced packaging capacity ensures supply chain throughput for multi-rack NVLink deployments.',
    impact: 'MEDIUM_HIGH',
    confidence: 90,
    momentum: 35,
    status: 'VALIDATED',
    evidenceIds: ['ev-004'],
    entityIds: ['ent-nvda', 'ent-tsmc'],
    sourceTypes: ['NEWS', 'COMPANY'],
    detectedAt: '2026-08-21T14:20:00Z',
    createdAt: '2026-08-21T14:20:00Z',
  },
];

export const seedRecommendations: RecommendationModel[] = [
  {
    id: 'rec-001',
    investigationId: 'inv-001',
    title: 'Upgrade Inference Runtime Pipeline',
    description: 'Refactor enterprise model serving layers to adopt native FP4 sub-byte quantization.',
    action: 'Upgrade inference runtime pipeline to native FP4 kernels',
    priority: 'HIGH',
    reason: 'Reduces operational server capex by 38% while maintaining output accuracy.',
    signalIds: ['sig-001'],
    createdAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'rec-002',
    investigationId: 'inv-001',
    title: 'Form Co-Design Packaging Partnerships',
    description: 'Secure long-term substrate agreements with advanced foundry partners.',
    action: 'Form strategic co-design packaging partnerships with TSMC',
    priority: 'HIGH',
    reason: 'Mitigates packaging capacity constraints during high-demand deployment cycles.',
    signalIds: ['sig-003'],
    createdAt: '2026-08-22T10:30:00Z',
  },
  {
    id: 'rec-003',
    investigationId: 'inv-001',
    title: 'Audit Competitor Latency Benchmarks',
    description: 'Evaluate wafer-scale engine performance on enterprise inference workloads.',
    action: 'Audit competitor latency metrics on enterprise benchmarks',
    priority: 'MEDIUM',
    reason: 'Tracks emerging wafer-scale competition from Cerebras & AMD.',
    signalIds: ['sig-002'],
    createdAt: '2026-08-22T10:30:00Z',
  },
];

export const seedTimelineEvents: TimelineEventModel[] = [
  {
    id: 'tl-001',
    investigationId: 'inv-001',
    title: 'USPTO Patent Published',
    description: 'NVIDIA files patent for low-precision FP4 tensor hardware units.',
    eventType: 'PATENT',
    date: '2026-08-18',
    entityIds: ['ent-nvda', 'ent-fp4'],
    evidenceIds: ['ev-001'],
    createdAt: '2026-08-20T10:32:00Z',
  },
  {
    id: 'tl-002',
    investigationId: 'inv-001',
    title: 'arXiv Memory Kernel Paper',
    description: 'Sub-linear attention paper published by researchers.',
    eventType: 'RESEARCH',
    date: '2026-08-19',
    entityIds: ['ent-nvda'],
    evidenceIds: ['ev-002'],
    createdAt: '2026-08-20T10:35:00Z',
  },
  {
    id: 'tl-003',
    investigationId: 'inv-001',
    title: 'Signal Validated by RadarX',
    description: 'AI Infrastructure Acceleration signal correlated across 3 source types.',
    eventType: 'SIGNAL',
    date: '2026-08-22',
    entityIds: ['ent-nvda', 'ent-fp4'],
    evidenceIds: ['ev-001', 'ev-002', 'ev-005'],
    createdAt: '2026-08-22T10:00:00Z',
  },
];

export const seedWatchlists: WatchlistModel[] = [
  {
    id: 'watch-001',
    name: 'NVIDIA × Generative AI Watch',
    title: 'NVIDIA × Generative AI Watch',
    organization: 'NVIDIA',
    technology: 'Generative AI',
    objective: "Continuously monitor NVIDIA's Generative AI hardware roadmap and competitive ASIC threats.",
    status: 'ACTIVE',
    entityIds: ['ent-nvda', 'ent-fp4', 'ent-tsmc'],
    investigationId: 'inv-001',
    monitoringMode: 'AUTO',
    currentSignal: 'AI Infrastructure Acceleration (+42% momentum)',
    confidence: 94,
    lastMeaningfulChange: '2h ago',
    activeAgents: ['Research', 'Patent', 'News', 'Competitor', 'Signal'],
    frequency: 'Continuous (24/7)',
    alertThreshold: 80,
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-08-22T10:30:00Z',
    lastCheckedAt: '2026-08-22T10:30:00Z',
    lastMeaningfulChangeAt: '2026-08-22T08:30:00Z',
  },
];

export const seedAlerts: AlertModel[] = [
  {
    id: 'alt-001',
    watchlistId: 'watch-001',
    investigationId: 'inv-001',
    signalId: 'sig-001',
    title: 'NVIDIA AI infrastructure acceleration signal detected',
    summary: 'High-confidence signal (+42% momentum) correlated across Patents, arXiv, and SEC records.',
    impact: 'HIGH',
    category: 'HIGH IMPACT',
    confidence: 94,
    evidenceCount: 14,
    timeAgo: '2h ago',
    read: false,
    createdAt: '2026-08-22T08:30:00Z',
  },
  {
    id: 'alt-002',
    watchlistId: 'watch-001',
    investigationId: 'inv-001',
    signalId: 'sig-002',
    title: 'Hyperscaler Custom ASIC capex shift detected',
    summary: 'Cloud providers allocating 25% inference capex to internal custom ASIC silicon.',
    impact: 'HIGH',
    category: 'THREAT',
    confidence: 88,
    evidenceCount: 9,
    timeAgo: '5h ago',
    read: true,
    createdAt: '2026-08-22T05:30:00Z',
  },
];

export const seedSources: SourceModel[] = [
  {
    id: 'src-001',
    name: 'USPTO Patent Database',
    category: 'PATENTS',
    status: 'active',
    coverage: 'Global Filings (US, WIPO, EPO)',
    lastSync: '10m ago',
    availability: 99.9,
    reliability: 98,
  },
  {
    id: 'src-002',
    name: 'arXiv Research Archive',
    category: 'RESEARCH',
    status: 'active',
    coverage: 'cs.AI, cs.CL, cs.DC Preprints',
    lastSync: '15m ago',
    availability: 99.8,
    reliability: 96,
  },
  {
    id: 'src-003',
    name: 'SEC EDGAR Filings',
    category: 'PUBLIC DATA',
    status: 'active',
    coverage: 'Form 10-K, 10-Q, 8-K Disclosures',
    lastSync: '30m ago',
    availability: 99.9,
    reliability: 99,
  },
  {
    id: 'src-004',
    name: 'Bloomberg Terminal Stream',
    category: 'NEWS',
    status: 'active',
    coverage: 'Financial & Tech Market Disclosures',
    lastSync: '5m ago',
    availability: 99.5,
    reliability: 95,
  },
  {
    id: 'src-005',
    name: 'GitHub Open Source API',
    category: 'WEB',
    status: 'active',
    coverage: 'CUDA & PyTorch Repository Commit Logs',
    lastSync: '12m ago',
    availability: 99.7,
    reliability: 94,
  },
  {
    id: 'src-006',
    name: 'Crossref Scientific Index',
    category: 'RESEARCH',
    status: 'active',
    coverage: 'Peer-Reviewed Journals',
    lastSync: '1h ago',
    availability: 99.4,
    reliability: 97,
  },
];
