'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Download, Printer } from 'lucide-react';
import { ExecutiveBriefModel, EvidenceModel } from '@/lib/types';

interface PdfExportButtonProps {
  brief: ExecutiveBriefModel;
  evidence: EvidenceModel[];
}

export function PdfExportButton({ brief, evidence }: PdfExportButtonProps) {
  const handlePrintPdf = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const content = `# RADARX EXECUTIVE INTELLIGENCE BRIEF
Objective ID: ${brief.investigationId}
Version: v${brief.version || 1}
Date: ${new Date(brief.generatedAt || Date.now()).toLocaleString()}

## EXECUTIVE SUMMARY
${brief.executiveSummary}

## MATERIAL CHANGES
${(brief.keyChanges || []).map((c) => `- [${c.changeType}] ${c.title}: ${c.description} (Magnitude: ${c.magnitude})`).join('\n')}

## STRATEGIC IMPLICATIONS
${(brief.strategicImplications || []).map((i) => `- ${i.topic}: ${i.implication}`).join('\n')}

## THREAT MATRIX
${(brief.threats || []).map((t) => `- ${t.title}: ${t.description} (Impact: ${t.impact})`).join('\n')}

## OPPORTUNITY MATRIX
${(brief.opportunities || []).map((o) => `- ${o.title}: ${o.description} (Potential Impact: ${o.potentialImpact})`).join('\n')}

## RECOMMENDED ACTIONS
${(brief.recommendedActions || []).map((r) => `- [${r.priority}] ${r.title}: ${r.action} (Confidence: ${r.confidence}%)`).join('\n')}

## PRIMARY EVIDENCE SOURCES (${evidence.length} ITEMS)
${evidence.map((e, idx) => `[${idx + 1}] ${e.title} (${e.sourceType})\n    Source: ${e.source}\n    URL: ${e.url || 'N/A'}\n    Date: ${e.publishedAt || 'N/A'}`).join('\n\n')}

---
Generated by RadarX Autonomous Intelligence Engine
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RadarX_Executive_Brief_${brief.investigationId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex items-center gap-2 print:hidden">
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handlePrintPdf}
        className="inline-flex items-center gap-2 bg-gradient-to-r from-[#D4AF37] via-[#C9A227] to-[#E0C46C] text-[#111827] font-mono text-xs font-extrabold px-4 py-2 rounded-xl shadow-md shadow-[#D4AF37]/20 hover:shadow-lg transition-all cursor-pointer"
      >
        <Printer className="w-4 h-4 text-[#111827]" />
        <span>EXPORT PDF REPORT</span>
      </motion.button>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handleDownloadMarkdown}
        className="inline-flex items-center gap-2 bg-white text-[#374151] hover:text-[#111827] font-mono text-xs font-bold px-4 py-2 rounded-xl border border-[#E5E7EB] hover:border-[#D4AF37]/50 shadow-xs transition-all cursor-pointer"
      >
        <Download className="w-4 h-4 text-[#8C6D13]" />
        <span>DOWNLOAD BRIEF (.MD)</span>
      </motion.button>
    </div>
  );
}

export default PdfExportButton;
